{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gremlin-integrations.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gremlin-integrations.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{ if .Values.serviceAccount.iamRole }}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.iamRole }}
    {{ end }}
{{- end }}